# Generated by Django 4.1 on 2022-09-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao_texto', models.CharField(max_length=200)),
                ('votos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Opções',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta_texto', models.CharField(max_length=200)),
                ('data_publicacao', models.DateTimeField(verbose_name='Data da Publicação')),
            ],
            options={
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='opcao',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pergunta'),
        ),
    ]
